services:
  api:
    build:
      dockerfile: infrastructure/docker/Dockerfile
      context: .
      target: build
    ports:
      - 8080:8080
    environment:
      JDBC_URL: "jdbc:postgresql://postgres/postgres?user=postgres&password=postgres"
      
  postgres:
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/init.sql