# SPDX-FileCopyrightText: 2025 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  webapp:
    build:
      dockerfile: ./infrastructure/docker/webapp.dockerfile
      context: .
      target: build
    ports:
      - ${WEBAPP_SERVER_PORT}:8080
    environment:
      JDBC_URL: ${WEBAPP_JDBC_URL}

  job:
    build:
      dockerfile: ./infrastructure/docker/job.dockerfile
      context: .
    environment:
      DATABASE_URL: ${JOB_DATABASE_URL}
      KEYCLOAK_BASE_URL: ${JOB_KEYCLOAK_BASE_URL}
      KEYCLOAK_REALM: ${JOB_KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${JOB_KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${JOB_KEYCLOAK_CLIENT_SECRET}
      METADATA_BASE_URL: ${JOB_METADATA_BASE_URL}
      DATASET_CONTENT_PAGE_LIMIT: ${JOB_DATASET_CONTENT_PAGE_LIMIT}
      LOG_LEVEL: ${JOB_LOG_LEVEL}
    depends_on:
      - postgres
      
  postgres:
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
