services:
  webapp:
    image: ${DOCKER_IMAGE_WEBAPP}:${DOCKER_TAG}
    restart: unless-stopped
    env_file: .env
    ports:
      - ${SERVER_PORT}:8080
  app:
    image: ${DOCKER_IMAGE_JOB}:${DOCKER_TAG}
    restart: unless-stopped
    env_file: .env